### ISSUE TITLE
Dislocación y borde de grano

### ISSUE THREAD

**Issue by ghost** [ciemat-tic/codec#151]

**Comment by plgm64** [comment]
1. Crear una dislocación en un monocristal rotado y comprobar la dinámica.

**Comment by plgm64** [comment]
Conseguido el setup de la  frontera Sigma 3 con dislocación a falta de minimizar
![Sigma3_GB_3.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1e804978872001181df9e/125516c66e82c728ace21e0d46db9d9d2e83d096a8cb8010e611b2843b492d762a10e17132d0ba7ebc402b505b0a1ca8170d5b44fcf8db2ea0bf3d77d84e17ff933c0120996048e6edc00db513bb28814e80b7bc8248c6e13f22e28b865d73.png)
![Sigma3_GB_2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1e804978872001181df9e/125516c66e82c728ace21e0d46db9d9d2e83d096a8cb8011e611b2843b492d762a10e17132d0ba7ebc402b505b0a1ca8170d5b44fcf8db2ea0bf3d77d84e17ff933c0120996048e6edc00db513bb27814e80b7bc8248c6e13f22e38f8c5d73.png)
![Captura de pantalla de 2017-11-16 16-27-44.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1e804978872001181df9e/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b45cfe80284a2b726900a66b22d5b27ff2132a4c5e595ead47455d43e1fd8d39baa47c32d5065ebe957f5566c33417ffea821ebb54e824dd1a81b6bc8b1ec5ee3424e0d99d532c5c5446dda0006ceacc09da52e44ae94754a112366be2703f7841961a7c3e26.png)

**Comment by plgm64** [comment]
Con el strain rate sugerido por Anna hacen falta del orden de nanosegundos para que la dislocación comience a moverse. Esto demanda muchos recursos computacionales, semanas de cálculo en Dirac (96 cores). El problema es que para verificar/validar un cálculo de test se pierde demasiado tiempo, lo cual no es viable en este estado del proyecto en el que se está desarrollando la metodología. Es necesario acelerar los cálculos. He iniciado pruebas en el CETA con GPUs Kepler

**Comment by plgm64** [comment]
Usando los mismos scripts de LAMMPS en las colas de CPU y GPU del CETA se obtienen resultados diferentes ???. Debe haber un bug en la codificación de la función 'minimize' en la versión de CUDA. No perdemos mas el tiempo con las GPUs de momento, en el futuro se contactará con los desarrolladores de LAMMPS.

Se ha conseguido simular la evolución de la dislocación y el borde de grano, ver:
http://sharedtemp.ciemat.es/index.php/s/oXtjMrT4G6B7DFJ

No obstante, Anna Serra opina que las curvas strain-stress no puede explicarse en base a la animación. Se procede a comparar las siguientes simulaciones con la obtenida de la dislocación con frontera:
1. Una dislocación sin frontera
2. Frontera sin dislocación
3. Cristal perfecto
para intentar identificar la fuente de stress adicional en las curvas.

**Comment by plgm64** [comment]
Por otro lado los ficheros de salida de LAMMPS  ya alcanzan los ~ 20 GB con los cual no es viable el post-procesado de los datos en local con la máquina de que se dispone de 4 GB de RAM.

Tras la última reunión de los lunes, al parecer no va a ser posible disponer de una estación de trabajo dedicada para poder seguir haciendo el post-procesado en local visualmente y teniendo en cuenta las limitaciones de la máquina disponible y hasta que los nodos de visualización se hagan realidad, se tendrá que hacer un post-procesado en remoto sin las facilidades de visualización de OVITO, es decir a ciegas con el add-on de python que trae OVITO, usando CPU.  Afortunadamente  esta aproximación permitirá hacer animaciones y extraer snapshots de los átomos de forma automatizada aunque como contrapartida se prevé llevará un par de meses de desarrollo el implementarla.

**Comment by plgm64** [comment]
Avances: 1. procesado de video en remoto con Tachyon (MPI)
                  2. Strain stress correct !
                  3. Nueva versión lammps + tolerancia menor = K80 funciona 1 core + 1 K80 = 64 cores (ahorro en consumo eléctrico):

![stress_strain_CPU_vs_GPU.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1e804978872001181df9e/125516c66e82c728ace21e0d46fb8088269190969cfdad42ad53cfb7197318653a3b841b45c7af6aaf50740b0a0c0abe4b4a5a4dfaaadb2ba7b269228e0a5ee9d16d5e26c33b18adbfd00da313f871d51bdaebe5c01982fa3737e683854e3b1f0d1889f9543da99e4cce4abb.png)
